# Generated by Django 5.1.15 on 2026-07-01 03:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nachname', models.CharField(max_length=80)),
                ('vorname', models.CharField(blank=True, max_length=80)),
                ('geburtsdatum', models.DateField(blank=True, null=True, verbose_name='geb. am')),
                ('al', models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='bewilligt FLS/Monat (AL)')),
                ('kle', models.DecimalField(decimal_places=3, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='davon kLE/Monat')),
                ('hbg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HBG')),
                ('kue_bis', models.DateField(blank=True, null=True, verbose_name='KÜ bis')),
                ('status', models.CharField(choices=[('Betreuung', 'Betreuung'), ('Beendigung', 'Beendigung')], default='Betreuung', max_length=12)),
                ('brp_bis', models.DateField(blank=True, null=True, verbose_name='BRP zu Teamleitung bis')),
                ('versendet_am', models.DateField(blank=True, null=True, verbose_name='… versendet am')),
                ('person_id', models.CharField(blank=True, max_length=40, verbose_name='Person-ID')),
                ('thfd', models.CharField(blank=True, max_length=120, verbose_name='Zuständigkeit THFD')),
                ('kommentar', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Klient*in',
                'verbose_name_plural': 'Belegungsliste (Klient*innen)',
                'ordering': ['nachname', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nachname')),
                ('vorname', models.CharField(blank=True, max_length=80, verbose_name='Vorname')),
                ('kuerzel', models.CharField(blank=True, max_length=10, verbose_name='Kürzel')),
                ('rolle', models.CharField(choices=[('betreuer', 'Betreuer*in'), ('teamleitung', 'Teamleitung')], default='betreuer', max_length=20)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mitarbeiter*in',
                'verbose_name_plural': 'Mitarbeiter*innen',
                'ordering': ['name', 'vorname'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField(default=2026, unique=True)),
                ('teamsitzung_wochentag', models.PositiveSmallIntegerField(default=3, help_text='0=Mo … 3=Do … 6=So')),
                ('teamsitzung_dauer_std', models.DecimalField(decimal_places=2, default=Decimal('3.0'), max_digits=4)),
                ('fls_preis', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='FLS-Preis €')),
            ],
            options={
                'verbose_name': 'Team-Parameter',
                'verbose_name_plural': 'Team-Parameter',
            },
        ),
        migrations.CreateModel(
            name='Gruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('thema', models.CharField(max_length=120)),
                ('leistungsart', models.CharField(choices=[('FS', 'FS – fallspezifische Leistung'), ('WFS', 'WFS – weitere fallspezifische Leistung'), ('BAO', 'BAO – Betreuung am anderen Ort'), ('FUS', 'FUS – fallunspezifische Leistung'), ('FZ', 'FZ – Fahrtzeit'), ('AL', 'AL – Assistenzleistung'), ('KLE', 'KLE – kalkulatorische Leistungseinheit'), ('FH', 'FH – Freihaltung/Abwesenheit (50 %)')], default='FS', max_length=4)),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('anz_ma', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Anz. Mitarbeiter')),
                ('teilnehmer', models.ManyToManyField(blank=True, related_name='gruppen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Gruppe',
                'verbose_name_plural': 'Gruppennachweise',
                'ordering': ['-datum'],
            },
        ),
        migrations.CreateModel(
            name='Leistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('leistungsart', models.CharField(choices=[('FS', 'FS – fallspezifische Leistung'), ('WFS', 'WFS – weitere fallspezifische Leistung'), ('BAO', 'BAO – Betreuung am anderen Ort'), ('FUS', 'FUS – fallunspezifische Leistung'), ('FZ', 'FZ – Fahrtzeit'), ('AL', 'AL – Assistenzleistung'), ('KLE', 'KLE – kalkulatorische Leistungseinheit'), ('FH', 'FH – Freihaltung/Abwesenheit (50 %)')], max_length=4)),
                ('taetigkeit', models.CharField(blank=True, max_length=120, verbose_name='Tätigkeit')),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('notiz', models.CharField(blank=True, max_length=255)),
                ('auto', models.BooleanField(default=False, verbose_name='automatisch')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leistungen', to='nachweis.klient')),
                ('betreuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leistungen', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Leistung',
                'verbose_name_plural': 'Leistungsnachweis',
                'ordering': ['-datum', 'beginn'],
            },
        ),
        migrations.AddField(
            model_name='klient',
            name='bezugsbetreuer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='klienten', to='nachweis.mitarbeiter', verbose_name='Bezugsbetreuer*in'),
        ),
        migrations.AddField(
            model_name='klient',
            name='vertretung1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertretung1_klienten', to='nachweis.mitarbeiter', verbose_name='Vertretung I'),
        ),
        migrations.AddField(
            model_name='klient',
            name='vertretung2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertretung2_klienten', to='nachweis.mitarbeiter', verbose_name='Vertretung II'),
        ),
    ]
