# Generated by Django 5.1.15 on 2026-07-01 04:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0002_mitarbeiter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='urlaubstage',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Urlaubstage/Jahr'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='wochenstunden',
            field=models.DecimalField(decimal_places=1, default=Decimal('39.0'), max_digits=4, verbose_name='Wochen-Soll (Std)'),
        ),
        migrations.CreateModel(
            name='Abwesenheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('Urlaub', 'Urlaub'), ('Freizeitausgleich', 'Freizeitausgleich'), ('Krank', 'Krank'), ('Fortbildung', 'Fortbildung'), ('Sonstige', 'Sonstige')], default='Urlaub', max_length=20)),
                ('von', models.DateField()),
                ('bis', models.DateField()),
                ('status', models.CharField(choices=[('beantragt', 'beantragt'), ('genehmigt', 'genehmigt'), ('abgelehnt', 'abgelehnt')], default='beantragt', max_length=12)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abwesenheiten', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Abwesenheit',
                'verbose_name_plural': 'Abwesenheiten',
                'ordering': ['-von'],
            },
        ),
        migrations.CreateModel(
            name='Arbeitszeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('beginn', models.TimeField(blank=True, null=True)),
                ('ende', models.TimeField(blank=True, null=True)),
                ('pause_min', models.PositiveSmallIntegerField(default=0, verbose_name='Pause (Min)')),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbeitszeiten', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Arbeitszeit',
                'verbose_name_plural': 'Arbeitszeiten',
                'ordering': ['-datum', 'beginn'],
            },
        ),
    ]
