# Generated by Django 5.1.15 on 2026-07-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0003_mitarbeiter_urlaubstage_mitarbeiter_wochenstunden_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('typ', models.CharField(choices=[('BEW', 'Betreutes Einzelwohnen (BEW)'), ('WG', 'Wohngemeinschaft (WG)'), ('Verwaltung', 'Verwaltung')], default='BEW', max_length=20)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='rolle',
            field=models.CharField(choices=[('user', 'User (Betreuer*in)'), ('leitung', 'Leitung'), ('admin', 'Administration')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='klient',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienten', to='nachweis.team', verbose_name='Team'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='leitet',
            field=models.ManyToManyField(blank=True, help_text='Nur für Rolle Leitung: welche Teams diese Person leitet.', related_name='leitungen', to='nachweis.team', verbose_name='leitet Team(s)'),
        ),
        migrations.AddField(
            model_name='mitarbeiter',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitglieder', to='nachweis.team', verbose_name='Team (Zugehörigkeit)'),
        ),
    ]
