# Generated by Django 5.1.15 on 2026-07-01 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0004_team_alter_mitarbeiter_rolle_klient_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stempelung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateTimeField()),
                ('ende', models.DateTimeField(blank=True, null=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stempelungen', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Stempelung',
                'verbose_name_plural': 'Stempelungen',
                'ordering': ['-beginn'],
            },
        ),
    ]
