# Generated by Django 5.1.15 on 2026-07-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0005_stempelung'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stempelung',
            constraint=models.UniqueConstraint(condition=models.Q(('ende__isnull', True)), fields=('mitarbeiter',), name='eine_offene_stempelung'),
        ),
    ]
