# Generated by Django 5.1.15 on 2026-07-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0006_stempelung_eine_offene_stempelung'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbeitszeit',
            name='status',
            field=models.CharField(choices=[('beantragt', 'beantragt'), ('genehmigt', 'genehmigt'), ('abgelehnt', 'abgelehnt')], default='beantragt', max_length=12),
        ),
    ]
