# Generated by Django 5.1.15 on 2026-07-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0007_arbeitszeit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(blank=True, max_length=80)),
                ('kostenstelle', models.CharField(blank=True, max_length=20, verbose_name='Kostenstellen-Code')),
                ('aktiv', models.BooleanField(default=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kasse', to='nachweis.team')),
            ],
            options={
                'verbose_name': 'Kasse',
                'verbose_name_plural': 'Kassen',
                'ordering': ['team__name'],
            },
        ),
        migrations.CreateModel(
            name='Kassenmonat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('vortrag', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kassenvortrag')),
                ('kasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monate', to='nachweis.kasse')),
            ],
            options={
                'verbose_name': 'Kassenmonat',
                'verbose_name_plural': 'Kassenmonate',
                'ordering': ['-jahr', '-monat'],
            },
        ),
        migrations.CreateModel(
            name='Kassenbuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bel_nr', models.PositiveIntegerField(verbose_name='Beleg-Nr.')),
                ('datum', models.DateField()),
                ('text', models.CharField(max_length=200)),
                ('einnahme', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ausgabe', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buchungsdatum', models.DateField(blank=True, null=True)),
                ('kontonr', models.CharField(blank=True, max_length=20, verbose_name='Kontonr.')),
                ('kostenstelle', models.CharField(blank=True, max_length=20, verbose_name='Kostenstellen-Code')),
                ('monat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='nachweis.kassenmonat')),
            ],
            options={
                'verbose_name': 'Kassenbuchung',
                'verbose_name_plural': 'Kassenbuchungen',
                'ordering': ['bel_nr', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Zaehlprotokoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('n100', models.PositiveIntegerField(default=0)),
                ('n50', models.PositiveIntegerField(default=0)),
                ('n20', models.PositiveIntegerField(default=0)),
                ('n10', models.PositiveIntegerField(default=0)),
                ('n5', models.PositiveIntegerField(default=0)),
                ('m2', models.PositiveIntegerField(default=0)),
                ('m1', models.PositiveIntegerField(default=0)),
                ('m050', models.PositiveIntegerField(default=0)),
                ('m020', models.PositiveIntegerField(default=0)),
                ('m010', models.PositiveIntegerField(default=0)),
                ('m005', models.PositiveIntegerField(default=0)),
                ('m002', models.PositiveIntegerField(default=0)),
                ('m001', models.PositiveIntegerField(default=0)),
                ('nicht_eingetragene', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='nicht eingetragene Belege')),
                ('vermerke', models.TextField(blank=True, verbose_name='Vermerke für die FiBu')),
                ('monat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zaehlung', to='nachweis.kassenmonat')),
            ],
            options={
                'verbose_name': 'Zählprotokoll',
                'verbose_name_plural': 'Zählprotokolle',
            },
        ),
        migrations.AddConstraint(
            model_name='kassenmonat',
            constraint=models.UniqueConstraint(fields=('kasse', 'jahr', 'monat'), name='ein_kassenmonat'),
        ),
    ]
