# Generated by Django 5.1.15 on 2026-07-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0008_kasse_kassenmonat_kassenbuchung_zaehlprotokoll_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='kuerzel',
            field=models.CharField(blank=True, help_text='Kurzzeichen für den Wochenkalender (leer = automatisch aus dem Namen)', max_length=6, verbose_name='Kürzel'),
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField(blank=True, null=True)),
                ('titel', models.CharField(blank=True, help_text='frei, z. B. für interne Termine ohne Klient*in', max_length=120, verbose_name='Titel')),
                ('ort', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('notiz', models.CharField(blank=True, max_length=255)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termine', to='nachweis.klient', verbose_name='Klient*in')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['datum', 'beginn'],
            },
        ),
    ]
