# Generated by Django 5.1.15 on 2026-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0009_klient_kuerzel_termin'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='arbeitszeit',
            index=models.Index(fields=['mitarbeiter', 'datum'], name='nachweis_ar_mitarbe_0791be_idx'),
        ),
        migrations.AddIndex(
            model_name='klient',
            index=models.Index(fields=['team', 'status'], name='nachweis_kl_team_id_c6984a_idx'),
        ),
        migrations.AddIndex(
            model_name='leistung',
            index=models.Index(fields=['klient', 'datum'], name='nachweis_le_klient__27ca2d_idx'),
        ),
        migrations.AddIndex(
            model_name='leistung',
            index=models.Index(fields=['betreuer', 'datum'], name='nachweis_le_betreue_217a45_idx'),
        ),
        migrations.AddIndex(
            model_name='termin',
            index=models.Index(fields=['mitarbeiter', 'datum'], name='nachweis_te_mitarbe_b04745_idx'),
        ),
        migrations.AddIndex(
            model_name='termin',
            index=models.Index(fields=['datum'], name='nachweis_te_datum_fb620c_idx'),
        ),
    ]
