# Generated by Django 5.1.15 on 2026-07-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0010_arbeitszeit_nachweis_ar_mitarbe_0791be_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leistung',
            name='dokumentation',
            field=models.TextField(blank=True, help_text='ausführlicher Verlaufstext bei Bedarf', verbose_name='Dokumentation'),
        ),
    ]
