# Generated by Django 5.2.15 on 2026-07-05 04:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0011_leistung_dokumentation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiederkehrendeLeistung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=80)),
                ('leistungsart', models.CharField(choices=[('FS', 'FS – fallspezifische Leistung'), ('WFS', 'WFS – weitere fallspezifische Leistung'), ('BAO', 'BAO – Betreuung am anderen Ort'), ('FUS', 'FUS – fallunspezifische Leistung'), ('FZ', 'FZ – Fahrtzeit'), ('AL', 'AL – Assistenzleistung'), ('KLE', 'KLE – kalkulatorische Leistungseinheit'), ('FH', 'FH – Freihaltung/Abwesenheit (50 %)')], default='KLE', max_length=4)),
                ('rhythmus', models.CharField(choices=[('woche', 'wöchentlich'), ('2woche', '14-täglich'), ('monat', 'monatlich'), ('quartal', 'vierteljährlich'), ('jahr', 'jährlich')], default='woche', max_length=8)),
                ('wochentag', models.PositiveSmallIntegerField(default=3, help_text='0=Mo … 3=Do … 6=So', verbose_name='Wochentag')),
                ('woche_im_monat', models.SmallIntegerField(default=0, help_text='Für monatlich per Wochentag: 1.–4., -1 = letzte. 0 = (Wochen-Rhythmus).', verbose_name='Woche im Monat')),
                ('tag_im_monat', models.PositiveSmallIntegerField(blank=True, help_text='1–31; wenn gesetzt, statt Wochentag-Regel (monatlich/…).', null=True, verbose_name='fester Tag im Monat')),
                ('monat_im_jahr', models.PositiveSmallIntegerField(blank=True, help_text='1–12: für jährlich (welcher Monat) bzw. vierteljährlich (Startmonat).', null=True, verbose_name='Anker-Monat')),
                ('dauer_std', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5, verbose_name='Dauer je Termin (Std)')),
                ('anrechnung', models.CharField(choices=[('teiler', '÷ Klient*innen in Betreuung'), ('fest', 'fester Wert je Klient*in'), ('kalender', 'nur Kalender (kein Nachweis)')], default='teiler', max_length=8)),
                ('wert_pro_klient', models.DecimalField(decimal_places=3, default=0, help_text="nur bei Anrechnung 'fester Wert'.", max_digits=6, verbose_name='fester Wert je Klient*in (Std)')),
                ('feiertage_aussparen', models.BooleanField(default=True, verbose_name='Berliner Feiertage aussparen')),
                ('im_kalender', models.BooleanField(default=True, verbose_name='im Kalender anzeigen')),
                ('gilt_ab', models.DateField(blank=True, null=True, verbose_name='gültig ab')),
                ('gilt_bis', models.DateField(blank=True, null=True, verbose_name='gültig bis')),
                ('aktiv', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serienleistungen', to='nachweis.team', verbose_name='Team (leer = alle Teams)')),
            ],
            options={
                'verbose_name': 'Wiederkehrende Leistung',
                'verbose_name_plural': 'Wiederkehrende Leistungen',
                'ordering': ['bezeichnung'],
            },
        ),
    ]
