# Generated by Django 5.2.15 on 2026-07-05 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0012_wiederkehrendeleistung'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='kostentraeger',
            field=models.CharField(blank=True, help_text='Bezirksamt / überörtlicher Träger – Rechnungsempfänger für die Abrechnung', max_length=120, verbose_name='Kostenträger'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='person_id',
            field=models.CharField(blank=True, max_length=40, verbose_name='Person-ID / Aktenzeichen'),
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20, unique=True, verbose_name='Rechnungsnummer')),
                ('empfaenger', models.CharField(max_length=120, verbose_name='Empfänger (Kostenträger)')),
                ('empfaenger_anschrift', models.TextField(blank=True, verbose_name='Anschrift')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('datum', models.DateField(verbose_name='Rechnungsdatum')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gestellt', 'gestellt'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert')], default='entwurf', max_length=10)),
                ('notiz', models.CharField(blank=True, max_length=255)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-datum', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='Monatsfreigabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('offen', 'offen'), ('eingereicht', 'fertiggestellt (MA)'), ('freigegeben', 'freigegeben (Leitung)'), ('abgerechnet', 'abgerechnet')], default='offen', max_length=12)),
                ('fls_summe', models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Σ FLS (festgeschrieben)')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Betrag € (festgeschrieben)')),
                ('hinweis', models.CharField(blank=True, max_length=255, verbose_name='Hinweis (Rückweisung)')),
                ('eingereicht_am', models.DateTimeField(blank=True, null=True)),
                ('freigegeben_am', models.DateTimeField(blank=True, null=True)),
                ('abgerechnet_am', models.DateTimeField(blank=True, null=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('eingereicht_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('freigegeben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='freigaben', to='nachweis.klient')),
                ('rechnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positionen', to='nachweis.rechnung')),
            ],
            options={
                'verbose_name': 'Monatsfreigabe',
                'verbose_name_plural': 'Monatsfreigaben',
                'ordering': ['-jahr', '-monat', 'klient__nachname'],
                'constraints': [models.UniqueConstraint(fields=('klient', 'jahr', 'monat'), name='eine_freigabe_pro_klient_monat')],
            },
        ),
    ]
