# Generated by Django 5.2.15 on 2026-07-05 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0013_klient_kostentraeger_alter_klient_person_id_rechnung_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kasse',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kasse', to='nachweis.team'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='klienten', to='nachweis.team', verbose_name='Team'),
        ),
        migrations.AddConstraint(
            model_name='kassenbuchung',
            constraint=models.UniqueConstraint(fields=('monat', 'bel_nr'), name='eine_belegnr_pro_kassenmonat'),
        ),
    ]
