# Generated by Django 5.2.15 on 2026-07-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0014_alter_kasse_team_alter_klient_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leistung',
            name='termin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumentationen', to='nachweis.termin'),
        ),
    ]
