# Generated by Django 5.2.15 on 2026-07-06 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0015_leistung_termin'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='kle_summe',
            field=models.DecimalField(decimal_places=3, default=0, help_text='kLE je Tag × Kalendertage des Monats (pauschal)', max_digits=8, verbose_name='Σ kLE (festgeschrieben, Std)'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='kle_je_tag',
            field=models.DecimalField(decimal_places=6, default=0, help_text='kalkulatorische Leistungseinheit – einheitlich für alle Klient*innen, je Kalendertag (Senats-Tool, Output 3.). Deckt fallunspezifische Zeiten, Erreichbarkeit, Wegezeiten, Sonstiges. 0 = kLE nicht in der Abrechnung.', max_digits=8, verbose_name='kLE je Leistungsberechtigte*m und Tag (Std)'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='fls_preis',
            field=models.DecimalField(decimal_places=4, default=0, help_text='€ je Fachleistungsstunde (Senats-Tool, Output 3.)', max_digits=8, verbose_name='FLS-Satz €'),
        ),
        migrations.CreateModel(
            name='HBGSatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hbg', models.PositiveSmallIntegerField(verbose_name='HBG')),
                ('fls_woche', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='individuelle FLS pro Woche (Std)')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hbg_saetze', to='nachweis.parameter')),
            ],
            options={
                'verbose_name': 'HBG-Satz (FLS/Woche)',
                'verbose_name_plural': 'HBG-Sätze (FLS/Woche)',
                'ordering': ['hbg'],
                'constraints': [models.UniqueConstraint(fields=('parameter', 'hbg'), name='ein_satz_pro_hbg_und_jahr')],
            },
        ),
    ]
