# Generated by Django 5.2.15 on 2026-07-06 14:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0016_monatsfreigabe_kle_summe_parameter_kle_je_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hbgsatz',
            name='belegung_stichtag',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Belegung am Stichtag'),
        ),
        migrations.AddField(
            model_name='hbgsatz',
            name='pauschale_alt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Maßnahmepauschale alt (€/Tag)'),
        ),
        migrations.CreateModel(
            name='Umrechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapazitaet', models.PositiveSmallIntegerField(default=0, verbose_name='vereinbarte Kapazität (Plätze)')),
                ('wochenarbeitszeit', models.DecimalField(decimal_places=2, default=Decimal('38.5'), max_digits=4, verbose_name='Wochenarbeitszeit (Std)')),
                ('auslastung', models.DecimalField(decimal_places=4, default=Decimal('0.959'), help_text='landesweit vereinbart 0,959 – abweichend anpassbar', max_digits=5, verbose_name='Auslastung')),
                ('fallunspez_anteil', models.DecimalField(decimal_places=3, default=Decimal('0.200'), max_digits=4, verbose_name='Anteil fallunspezifische Zeiten')),
                ('erreichbarkeit_mo_fr_std', models.DecimalField(decimal_places=2, default=0, help_text='Anzahl Mitarb. × Stunden, z. B. 1 MA 10–16 Uhr = 6', max_digits=6, verbose_name='Erreichbarkeit Mo–Fr (Std je Tag)')),
                ('erreichbarkeit_we_ft_std', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Erreichbarkeit Sa/So/Feiertag (Std je Tag)')),
                ('wegezeit_std_vk_woche', models.DecimalField(decimal_places=2, default=Decimal('6'), max_digits=5, verbose_name='Ø Wegezeit je VK/Woche (Std)')),
                ('pk_alternativ', models.DecimalField(decimal_places=2, default=0, help_text='0 = Differenzmethode aus den Maßnahmepauschalen (wie das Senats-Tool)', max_digits=12, verbose_name='Ø-Personalkosten alternativ €')),
                ('parameter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='umrechnung', to='nachweis.parameter')),
            ],
            options={
                'verbose_name': 'Umrechnung (Senats-Tool-Eingaben)',
                'verbose_name_plural': 'Umrechnungen (Senats-Tool-Eingaben)',
            },
        ),
    ]
