# Generated by Django 5.2.15 on 2026-07-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0017_hbgsatz_belegung_stichtag_hbgsatz_pauschale_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='fls_einzeln',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='davon einzeln erbracht'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='fls_gruppe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='davon in Gruppe erbracht'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='soll_fls',
            field=models.DecimalField(decimal_places=3, default=0, help_text='bewilligte FLS/Monat (§ 18 Abs. 3 Buchst. d)', max_digits=8, verbose_name='Σ FLS nach Bescheid (Monat)'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='vorschuss',
            field=models.DecimalField(decimal_places=2, default=0, help_text='(Soll-FLS + Ø-kLE/Monat) × FLS-Satz (§ 18 Abs. 2)', max_digits=12, verbose_name='bewilligter Vorschuss €'),
        ),
        migrations.AlterField(
            model_name='monatsfreigabe',
            name='fls_summe',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Σ FLS Ist (festgeschrieben)'),
        ),
        migrations.AlterField(
            model_name='monatsfreigabe',
            name='kle_summe',
            field=models.DecimalField(decimal_places=3, default=0, help_text='kLE je Tag × Kalendertage des Monats (pauschal, § 18 Abs. 1 b)', max_digits=8, verbose_name='Σ kLE (festgeschrieben, Std)'),
        ),
    ]
