# Generated by Django 5.2.15 on 2026-07-06 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0018_monatsfreigabe_fls_einzeln_monatsfreigabe_fls_gruppe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kasse',
            name='verantwortlich',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassen_verantwortlich', to='nachweis.mitarbeiter', verbose_name='Kassenverantwortliche*r'),
        ),
        migrations.AddField(
            model_name='kasse',
            name='vertretung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kassen_vertretung', to='nachweis.mitarbeiter', verbose_name='Vertretung'),
        ),
    ]
