# Generated by Django 5.2.15 on 2026-07-09 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0019_kasse_verantwortlich_kasse_vertretung'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kostentraeger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('typ', models.CharField(choices=[('Bezirksamt', 'Bezirksamt'), ('überörtlich', 'überörtlicher Träger'), ('Selbstzahler', 'Selbstzahler'), ('Sonstige', 'Sonstige')], default='Bezirksamt', max_length=20)),
                ('amt', models.CharField(blank=True, max_length=140, verbose_name='Amt / Fachbereich')),
                ('adresse', models.TextField(blank=True, verbose_name='Anschrift')),
                ('ansprechpartner', models.CharField(blank=True, max_length=140)),
                ('leitweg_id', models.CharField(blank=True, max_length=60, verbose_name='Leitweg-ID (XRechnung)')),
                ('zahlungsziel_tage', models.PositiveSmallIntegerField(default=30, verbose_name='Zahlungsziel (Tage)')),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kostenträger',
                'verbose_name_plural': 'Kostenträger',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bewilligung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktenzeichen', models.CharField(blank=True, max_length=60, verbose_name='Aktenzeichen')),
                ('leistungstyp', models.CharField(choices=[('FLS', 'Fachleistungsstunden + kLE')], default='FLS', max_length=8)),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='bewilligt ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='bewilligt bis')),
                ('fls_woche', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='FLS/Woche (bewilligt)')),
                ('kle_tag', models.DecimalField(decimal_places=6, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='kLE/Tag')),
                ('hbg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HBG (Herkunft)')),
                ('status', models.CharField(choices=[('aktiv', 'aktiv'), ('abgelaufen', 'abgelaufen'), ('storniert', 'storniert')], default='aktiv', max_length=12)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bewilligungen', to='nachweis.klient')),
                ('vorgaenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nachfolger', to='nachweis.bewilligung', verbose_name='Fortschreibung von')),
                ('kostentraeger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bewilligungen', to='nachweis.kostentraeger')),
            ],
            options={
                'verbose_name': 'Bewilligung',
                'verbose_name_plural': 'Bewilligungen',
                'ordering': ['-gueltig_von', '-erstellt'],
                'indexes': [models.Index(fields=['klient', 'status'], name='nachweis_be_klient__41a185_idx')],
            },
        ),
    ]
