# Generated by Django 5.2.15 on 2026-07-09 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0021_bewilligung_aus_bestand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechnungssteller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=160, verbose_name='Name / Träger')),
                ('strasse', models.CharField(blank=True, max_length=160, verbose_name='Straße + Nr.')),
                ('plz', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(blank=True, max_length=100, verbose_name='Ort')),
                ('land', models.CharField(default='DE', max_length=2, verbose_name='Ländercode')),
                ('ust_id', models.CharField(blank=True, max_length=20, verbose_name='USt-IdNr. (BT-31)')),
                ('steuernummer', models.CharField(blank=True, max_length=30, verbose_name='Steuernummer (BT-32)')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC')),
                ('bank', models.CharField(blank=True, max_length=120, verbose_name='Kreditinstitut')),
                ('zahlungsziel_tage', models.PositiveSmallIntegerField(default=30, verbose_name='Zahlungsziel (Tage)')),
                ('kontakt_name', models.CharField(blank=True, max_length=120, verbose_name='Ansprechpartner*in')),
                ('kontakt_tel', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('kontakt_mail', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('ust_befreit', models.BooleanField(default=True, verbose_name='umsatzsteuerbefreit')),
                ('befreiungsgrund', models.CharField(default='Steuerfrei nach § 4 Nr. 16 UStG', max_length=200, verbose_name='Befreiungsgrund')),
            ],
            options={
                'verbose_name': 'Rechnungssteller',
                'verbose_name_plural': 'Rechnungssteller',
            },
        ),
        migrations.AddField(
            model_name='rechnung',
            name='kostentraeger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechnungen', to='nachweis.kostentraeger'),
        ),
    ]
