# Generated by Django 5.2.15 on 2026-07-13 14:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0022_rechnungssteller_rechnung_kostentraeger'),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='faellig_am',
            field=models.DateField(blank=True, help_text='Rechnungsdatum + Zahlungsziel (beim Erstellen gesetzt)', null=True, verbose_name='fällig am'),
        ),
        migrations.CreateModel(
            name='Zahlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Zahlungseingang')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zahlungen', to='nachweis.rechnung')),
            ],
            options={
                'verbose_name': 'Zahlung',
                'verbose_name_plural': 'Zahlungen',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Mahnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stufe', models.PositiveSmallIntegerField(choices=[(1, 'Zahlungserinnerung'), (2, '1. Mahnung'), (3, '2. Mahnung (letzte)')])),
                ('datum', models.DateField(verbose_name='Mahndatum')),
                ('frist_tage', models.PositiveSmallIntegerField(default=14, verbose_name='Zahlungsfrist (Tage)')),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahnungen', to='nachweis.rechnung')),
            ],
            options={
                'verbose_name': 'Mahnung',
                'verbose_name_plural': 'Mahnungen',
                'ordering': ['-datum', '-stufe'],
                'constraints': [models.UniqueConstraint(fields=('rechnung', 'stufe'), name='eine_mahnung_je_stufe')],
            },
        ),
    ]
