# Generated by Django 5.2.15 on 2026-07-13 15:31

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0023_rechnung_faellig_am_zahlung_mahnung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rechnung',
            name='storno_zu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gutschriften', to='nachweis.rechnung', verbose_name='Gutschrift zu'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='typ',
            field=models.CharField(choices=[('rechnung', 'Rechnung'), ('gutschrift', 'Gutschrift (Storno)')], default='rechnung', max_length=12),
        ),
        migrations.CreateModel(
            name='HistoricalBewilligung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('aktenzeichen', models.CharField(blank=True, max_length=60, verbose_name='Aktenzeichen')),
                ('leistungstyp', models.CharField(choices=[('FLS', 'Fachleistungsstunden + kLE')], default='FLS', max_length=8)),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='bewilligt ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='bewilligt bis')),
                ('fls_woche', models.DecimalField(decimal_places=4, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='FLS/Woche (bewilligt)')),
                ('kle_tag', models.DecimalField(decimal_places=6, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='kLE/Tag')),
                ('hbg', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HBG (Herkunft)')),
                ('status', models.CharField(choices=[('aktiv', 'aktiv'), ('abgelaufen', 'abgelaufen'), ('storniert', 'storniert')], default='aktiv', max_length=12)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
                ('kostentraeger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.kostentraeger')),
                ('vorgaenger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.bewilligung', verbose_name='Fortschreibung von')),
            ],
            options={
                'verbose_name': 'historical Bewilligung',
                'verbose_name_plural': 'historical Bewilligungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRechnung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nummer', models.CharField(db_index=True, max_length=20, verbose_name='Rechnungsnummer')),
                ('typ', models.CharField(choices=[('rechnung', 'Rechnung'), ('gutschrift', 'Gutschrift (Storno)')], default='rechnung', max_length=12)),
                ('empfaenger', models.CharField(max_length=120, verbose_name='Empfänger (Kostenträger)')),
                ('empfaenger_anschrift', models.TextField(blank=True, verbose_name='Anschrift')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('datum', models.DateField(verbose_name='Rechnungsdatum')),
                ('faellig_am', models.DateField(blank=True, help_text='Rechnungsdatum + Zahlungsziel (beim Erstellen gesetzt)', null=True, verbose_name='fällig am')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gestellt', 'gestellt'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert')], default='entwurf', max_length=10)),
                ('notiz', models.CharField(blank=True, max_length=255)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('erstellt_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kostentraeger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.kostentraeger')),
                ('storno_zu', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.rechnung', verbose_name='Gutschrift zu')),
            ],
            options={
                'verbose_name': 'historical Rechnung',
                'verbose_name_plural': 'historical Rechnungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
