# Generated by Django 5.2.15 on 2026-07-13 20:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0024_rechnung_storno_zu_rechnung_typ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('richtungsziel', 'Richtungsziel'), ('handlungsziel', 'Handlungsziel')], default='handlungsziel', max_length=16)),
                ('titel', models.CharField(max_length=200, verbose_name='Ziel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung / Handlungsschritte')),
                ('indikator', models.TextField(blank=True, help_text='Woran erkennen wir, dass das Ziel erreicht ist?', verbose_name='Indikator der Zielerreichung')),
                ('status', models.CharField(choices=[('aktiv', 'aktiv'), ('erreicht', 'erreicht'), ('angepasst', 'angepasst (fortgeschrieben)'), ('aufgegeben', 'nicht weiterverfolgt')], default='aktiv', max_length=12)),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='vereinbart am')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='Zielhorizont')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ziele', to='nachweis.klient')),
                ('uebergeordnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unterziele', to='nachweis.ziel', verbose_name='gehört zu (Richtungsziel)')),
            ],
            options={
                'verbose_name': 'Ziel',
                'verbose_name_plural': 'Ziele',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalZiel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('art', models.CharField(choices=[('richtungsziel', 'Richtungsziel'), ('handlungsziel', 'Handlungsziel')], default='handlungsziel', max_length=16)),
                ('titel', models.CharField(max_length=200, verbose_name='Ziel')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung / Handlungsschritte')),
                ('indikator', models.TextField(blank=True, help_text='Woran erkennen wir, dass das Ziel erreicht ist?', verbose_name='Indikator der Zielerreichung')),
                ('status', models.CharField(choices=[('aktiv', 'aktiv'), ('erreicht', 'erreicht'), ('angepasst', 'angepasst (fortgeschrieben)'), ('aufgegeben', 'nicht weiterverfolgt')], default='aktiv', max_length=12)),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='vereinbart am')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='Zielhorizont')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('geaendert', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
                ('uebergeordnet', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.ziel', verbose_name='gehört zu (Richtungsziel)')),
            ],
            options={
                'verbose_name': 'historical Ziel',
                'verbose_name_plural': 'historical Ziele',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='leistung',
            name='ziele',
            field=models.ManyToManyField(blank=True, related_name='leistungen', to='nachweis.ziel'),
        ),
        migrations.AddIndex(
            model_name='ziel',
            index=models.Index(fields=['klient', 'status'], name='nachweis_zi_klient__659fb4_idx'),
        ),
    ]
