# Generated by Django 5.2.15 on 2026-07-13 20:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0025_ziel_historicalziel_leistung_ziele_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berichtsvorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bereich', models.CharField(blank=True, help_text='z. B. EGH, Jugendhilfe – rein informativ', max_length=60)),
                ('beschreibung', models.CharField(blank=True, max_length=255)),
                ('abschnitte', models.JSONField(blank=True, default=list, help_text='Liste der Abschnitts-Überschriften', verbose_name='Gliederung')),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Berichtsvorlage',
                'verbose_name_plural': 'Berichtsvorlagen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBericht',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('zeitraum_von', models.DateField(blank=True, null=True, verbose_name='Berichtszeitraum von')),
                ('zeitraum_bis', models.DateField(blank=True, null=True, verbose_name='Berichtszeitraum bis')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='fällig am')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('in_arbeit', 'in Arbeit'), ('besprochen', 'mit Klient*in besprochen'), ('versendet', 'versendet')], default='offen', max_length=12)),
                ('besprochen_am', models.DateField(blank=True, null=True)),
                ('versendet_am', models.DateField(blank=True, null=True)),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('geaendert', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('erstellt_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
                ('vorlage', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.berichtsvorlage')),
            ],
            options={
                'verbose_name': 'historical Bericht',
                'verbose_name_plural': 'historical Berichte',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zeitraum_von', models.DateField(blank=True, null=True, verbose_name='Berichtszeitraum von')),
                ('zeitraum_bis', models.DateField(blank=True, null=True, verbose_name='Berichtszeitraum bis')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='fällig am')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('in_arbeit', 'in Arbeit'), ('besprochen', 'mit Klient*in besprochen'), ('versendet', 'versendet')], default='offen', max_length=12)),
                ('inhalt', models.TextField(blank=True, help_text='entsteht i. d. R. KI-gestützt in FEGH-Bericht (TeilhabeAssist)', verbose_name='Berichtstext')),
                ('besprochen_am', models.DateField(blank=True, null=True)),
                ('versendet_am', models.DateField(blank=True, null=True)),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berichte', to='nachweis.klient')),
                ('vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='berichte', to='nachweis.berichtsvorlage')),
            ],
            options={
                'verbose_name': 'Bericht',
                'verbose_name_plural': 'Berichte',
                'ordering': ['-faellig_am', '-id'],
                'indexes': [models.Index(fields=['klient', 'status'], name='nachweis_be_klient__b77c4b_idx')],
            },
        ),
    ]
