# Generated by Django 5.2.15 on 2026-07-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0027_berichtsvorlagen_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bericht',
            name='exportiert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbericht',
            name='exportiert_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
