# Generated by Django 5.2.15 on 2026-07-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0028_bericht_exportiert_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leistung',
            name='unterschrieben_am',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leistung',
            name='unterschrift',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
