# Generated by Django 5.2.15 on 2026-07-14 01:48

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0029_leistung_unterschrieben_am_leistung_unterschrift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leistungskatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('rechtsgrundlage', models.CharField(blank=True, help_text='z. B. SGB IX §§ 113 ff. / SGB VIII § 31', max_length=80)),
                ('einheit', models.CharField(choices=[('fls_stunde', 'Fachleistungsstunde (dokumentiert)'), ('kle_tag', 'kLE je Kalendertag (pauschal)'), ('tagessatz', 'Tagessatz je Belegungstag'), ('oeffnungstag', 'Tagessatz je Öffnungstag (teilstationär)'), ('pauschale', 'Pauschale (je Monat/Ereignis)')], default='fls_stunde', max_length=16)),
                ('beschreibung', models.CharField(blank=True, max_length=255)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leistungskatalog-Eintrag',
                'verbose_name_plural': 'Leistungskatalog',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEntgeltsatz',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('variante', models.CharField(blank=True, help_text='z. B. „mit Leitungsanteil“ / „ohne“', max_length=60)),
                ('gueltig_von', models.DateField(verbose_name='gültig ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='gültig bis')),
                ('betrag', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Betrag €')),
                ('betrag_nebenkosten', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='davon Nebenkosten €')),
                ('betrag_investition', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='davon Investition €')),
                ('kommentar', models.CharField(blank=True, help_text='z. B. Beschluss-Nr. der Fortschreibung', max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kostentraeger', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.kostentraeger', verbose_name='Kostenträger (leer = alle)')),
                ('katalog', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.leistungskatalog')),
            ],
            options={
                'verbose_name': 'historical Entgeltsatz',
                'verbose_name_plural': 'historical Entgeltsätze',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='bewilligung',
            name='katalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bewilligungen', to='nachweis.leistungskatalog'),
        ),
        migrations.AddField(
            model_name='historicalbewilligung',
            name='katalog',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.leistungskatalog'),
        ),
        migrations.CreateModel(
            name='Entgeltsatz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variante', models.CharField(blank=True, help_text='z. B. „mit Leitungsanteil“ / „ohne“', max_length=60)),
                ('gueltig_von', models.DateField(verbose_name='gültig ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='gültig bis')),
                ('betrag', models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Betrag €')),
                ('betrag_nebenkosten', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='davon Nebenkosten €')),
                ('betrag_investition', models.DecimalField(decimal_places=4, default=0, max_digits=9, verbose_name='davon Investition €')),
                ('kommentar', models.CharField(blank=True, help_text='z. B. Beschluss-Nr. der Fortschreibung', max_length=200)),
                ('kostentraeger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entgeltsaetze', to='nachweis.kostentraeger', verbose_name='Kostenträger (leer = alle)')),
                ('katalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saetze', to='nachweis.leistungskatalog')),
            ],
            options={
                'verbose_name': 'Entgeltsatz',
                'verbose_name_plural': 'Entgeltsätze',
                'ordering': ['katalog', '-gueltig_von'],
                'indexes': [models.Index(fields=['katalog', 'gueltig_von'], name='nachweis_en_katalog_f7be72_idx')],
            },
        ),
    ]
