# Generated by Django 5.2.15 on 2026-07-14 01:57

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0031_leistungskatalog_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbwesenheitsartKlient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('kuerzel', models.CharField(help_text='fürs Kalenderraster, z. B. KH', max_length=4)),
                ('verguetung_prozent', models.PositiveSmallIntegerField(default=100, help_text='Anteil des Tagessatzes innerhalb der Weiterzahlungsgrenze', verbose_name='Vergütung %')),
                ('abzug_je_tag', models.DecimalField(decimal_places=2, default=0, help_text='z. B. Beköstigungssatz beim EGH-Freihaltegeld', max_digits=7, verbose_name='Abzug €/Tag')),
                ('max_tage', models.PositiveSmallIntegerField(blank=True, help_text='leer = unbegrenzt; darüber 0 % Vergütung', null=True, verbose_name='Weiterzahlungsgrenze (Tage)')),
                ('basis', models.CharField(choices=[('ereignis', 'je Ereignis (zusammenhängend)'), ('jahr', 'kumulativ je Kalenderjahr')], default='ereignis', max_length=10)),
                ('meldefrist_tage', models.PositiveSmallIntegerField(blank=True, help_text='Warnung, wenn die Abwesenheit länger dauert und nicht gemeldet ist (BRV Jug: Meldung ans Jugendamt ab dem 4. Tag → 3)', null=True, verbose_name='Meldefrist (Tage)')),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Abwesenheitsart (Klient)',
                'verbose_name_plural': 'Abwesenheitsarten (Klient)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('typ', models.CharField(choices=[('bew', 'BEW / TBEW (ambulant, Einzelwohnen)'), ('wg', 'WG / verbundene Wohnform (EGH)'), ('wohnform', 'besondere Wohnform (EGH, ehem. stationär)'), ('wohngruppe', 'Wohngruppe Jugendhilfe (§ 34/35a SGB VIII)'), ('tagesgruppe', 'Tagesgruppe (§ 32 SGB VIII, teilstationär)')], default='wg', max_length=16)),
                ('erreichbarkeit', models.CharField(choices=[('ohne', 'ohne besondere Erreichbarkeit'), ('tag', 'Tag-Präsenz'), ('nacht', 'Nacht-Bereitschaft/-Präsenz'), ('tag_nacht', 'Tag + Nacht (24h)')], default='ohne', max_length=12)),
                ('plaetze', models.PositiveSmallIntegerField(default=0, verbose_name='Plätze')),
                ('betriebserlaubnis', models.CharField(blank=True, max_length=80, verbose_name='Betriebserlaubnis (§ 45 SGB VIII) / Kennung')),
                ('adresse', models.CharField(blank=True, max_length=160)),
                ('aktiv', models.BooleanField(default=True)),
                ('katalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='angebote', to='nachweis.leistungskatalog', verbose_name='Standard-Leistungstyp (Abrechnung)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='angebote', to='nachweis.team')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Belegung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platz', models.CharField(blank=True, max_length=40, verbose_name='Platz/Zimmer')),
                ('einzug', models.DateField()),
                ('auszug', models.DateField(blank=True, null=True)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='belegungen', to='nachweis.angebot')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belegungen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Belegung',
                'verbose_name_plural': 'Belegungen',
                'ordering': ['-einzug'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBelegung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('platz', models.CharField(blank=True, max_length=40, verbose_name='Platz/Zimmer')),
                ('einzug', models.DateField()),
                ('auszug', models.DateField(blank=True, null=True)),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('angebot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.angebot')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'historical Belegung',
                'verbose_name_plural': 'historical Belegungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKlientAbwesenheit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('von', models.DateField(verbose_name='abwesend ab (Abreisetag)')),
                ('bis', models.DateField(blank=True, help_text='leer = dauert an', null=True, verbose_name='letzter Abwesenheitstag')),
                ('gemeldet_am', models.DateField(blank=True, null=True, verbose_name='dem Kostenträger gemeldet am')),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('art', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.abwesenheitsartklient')),
                ('belegung', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.belegung')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Klienten-Abwesenheit',
                'verbose_name_plural': 'historical Klienten-Abwesenheiten',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KlientAbwesenheit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateField(verbose_name='abwesend ab (Abreisetag)')),
                ('bis', models.DateField(blank=True, help_text='leer = dauert an', null=True, verbose_name='letzter Abwesenheitstag')),
                ('gemeldet_am', models.DateField(blank=True, null=True, verbose_name='dem Kostenträger gemeldet am')),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abwesenheiten', to='nachweis.abwesenheitsartklient')),
                ('belegung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abwesenheiten', to='nachweis.belegung')),
            ],
            options={
                'verbose_name': 'Klienten-Abwesenheit',
                'verbose_name_plural': 'Klienten-Abwesenheiten',
                'ordering': ['-von'],
            },
        ),
        migrations.AddIndex(
            model_name='belegung',
            index=models.Index(fields=['angebot', 'einzug'], name='nachweis_be_angebot_700168_idx'),
        ),
    ]
