# Generated by Django 5.2.15 on 2026-07-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0033_abwesenheitsarten_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klientabwesenheit',
            options={'ordering': ['-von', '-id'], 'verbose_name': 'Klienten-Abwesenheit', 'verbose_name_plural': 'Klienten-Abwesenheiten'},
        ),
        migrations.RemoveField(
            model_name='historicalklientabwesenheit',
            name='kommentar',
        ),
    ]
