# Generated by Django 5.2.15 on 2026-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0034_alter_klientabwesenheit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='abrechnungsart',
            field=models.CharField(choices=[('fls', 'FLS + kLE'), ('tagessatz', 'Tagessatz')], default='fls', max_length=12),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='belegungstage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Belegungstage (festgeschrieben)'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='verguetet_tage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='vergütete Tage (Äquivalent)'),
        ),
    ]
