# Generated by Django 5.2.15 on 2026-07-14 12:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0035_monatsfreigabe_abrechnungsart_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kostentraeger',
            name='debitorenkonto',
            field=models.CharField(blank=True, help_text='für den Buchungsstapel-Export (P4b)', max_length=9, verbose_name='DATEV Debitorenkonto'),
        ),
        migrations.AddField(
            model_name='rechnungssteller',
            name='datev_berater',
            field=models.CharField(blank=True, max_length=7, verbose_name='DATEV Berater-Nr.'),
        ),
        migrations.AddField(
            model_name='rechnungssteller',
            name='datev_erloeskonto',
            field=models.CharField(blank=True, help_text='z. B. steuerfreie Umsätze – mit dem Steuerbüro abstimmen', max_length=8, verbose_name='DATEV Erlöskonto'),
        ),
        migrations.AddField(
            model_name='rechnungssteller',
            name='datev_mandant',
            field=models.CharField(blank=True, max_length=5, verbose_name='DATEV Mandanten-Nr.'),
        ),
        migrations.CreateModel(
            name='HistoricalVorkommnis',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Vorfallsdatum')),
                ('uhrzeit', models.TimeField(blank=True, null=True)),
                ('kategorie', models.CharField(choices=[('gewalt', 'Gewaltvorfall / Übergriff (§ 37a SGB IX)'), ('kindeswohl', 'Gefährdungseinschätzung (§ 8a SGB VIII)'), ('unfall', 'Unfall / medizinischer Notfall'), ('medikation', 'Medikationsfehler'), ('beschwerde', 'Beschwerde'), ('sonstig', 'sonstiges besonderes Vorkommnis')], max_length=12)),
                ('gemeldet_an', models.CharField(blank=True, help_text='z. B. WTG-Aufsicht, Jugendamt, Kostenträger, Polizei', max_length=160, verbose_name='gemeldet an')),
                ('gemeldet_am', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'offen'), ('in_bearbeitung', 'in Bearbeitung'), ('abgeschlossen', 'abgeschlossen')], default='offen', max_length=16)),
                ('abgeschlossen_am', models.DateField(blank=True, null=True)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('geaendert', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('abgeschlossen_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('angebot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.angebot')),
                ('erstellt_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient', verbose_name='betroffene Klient*in (optional)')),
                ('team', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.team')),
            ],
            options={
                'verbose_name': 'historical Vorkommnis',
                'verbose_name_plural': 'historical Vorkommnisse',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Vorkommnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Vorfallsdatum')),
                ('uhrzeit', models.TimeField(blank=True, null=True)),
                ('kategorie', models.CharField(choices=[('gewalt', 'Gewaltvorfall / Übergriff (§ 37a SGB IX)'), ('kindeswohl', 'Gefährdungseinschätzung (§ 8a SGB VIII)'), ('unfall', 'Unfall / medizinischer Notfall'), ('medikation', 'Medikationsfehler'), ('beschwerde', 'Beschwerde'), ('sonstig', 'sonstiges besonderes Vorkommnis')], max_length=12)),
                ('beschreibung', models.TextField(verbose_name='Was ist passiert?')),
                ('sofortmassnahmen', models.TextField(blank=True, verbose_name='Sofortmaßnahmen')),
                ('massnahmen', models.TextField(blank=True, help_text='Pflicht vor dem Abschluss', verbose_name='Auswertung / abgeleitete Maßnahmen')),
                ('gemeldet_an', models.CharField(blank=True, help_text='z. B. WTG-Aufsicht, Jugendamt, Kostenträger, Polizei', max_length=160, verbose_name='gemeldet an')),
                ('gemeldet_am', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('offen', 'offen'), ('in_bearbeitung', 'in Bearbeitung'), ('abgeschlossen', 'abgeschlossen')], default='offen', max_length=16)),
                ('abgeschlossen_am', models.DateField(blank=True, null=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('abgeschlossen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('angebot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorkommnisse', to='nachweis.angebot')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vorkommnisse', to='nachweis.klient', verbose_name='betroffene Klient*in (optional)')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vorkommnisse', to='nachweis.team')),
            ],
            options={
                'verbose_name': 'Vorkommnis',
                'verbose_name_plural': 'Vorkommnisse',
                'ordering': ['-datum', '-id'],
                'indexes': [models.Index(fields=['team', 'status'], name='nachweis_vo_team_id_abc28f_idx')],
            },
        ),
    ]
