# Generated by Django 5.2.15 on 2026-07-14 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0036_kostentraeger_debitorenkonto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schichtart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('kuerzel', models.CharField(max_length=3)),
                ('beginn', models.TimeField()),
                ('ende', models.TimeField(help_text='vor `beginn` = Schicht über Mitternacht')),
                ('farbe', models.CharField(default='#0e7490', help_text='Hex-Farbe fürs Planraster', max_length=7)),
                ('ist_nachtdienst', models.BooleanField(default=False, help_text='zählt für die Nachtbesetzungs-Prüfung')),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schichtart',
                'verbose_name_plural': 'Schichtarten',
                'ordering': ['beginn', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('notiz', models.CharField(blank=True, max_length=120)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('angebot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dienste', to='nachweis.angebot')),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dienste', to='nachweis.mitarbeiter')),
                ('schichtart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dienste', to='nachweis.schichtart')),
            ],
            options={
                'verbose_name': 'Dienst',
                'verbose_name_plural': 'Dienste',
                'ordering': ['datum'],
                'indexes': [models.Index(fields=['datum'], name='nachweis_di_datum_71876e_idx')],
                'constraints': [models.UniqueConstraint(fields=('mitarbeiter', 'datum', 'schichtart'), name='ein_dienst_je_ma_tag_schicht')],
            },
        ),
    ]
