# Generated by Django 5.2.15 on 2026-07-14 13:50

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0038_schichtarten_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wirkungsdimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bereich', models.CharField(choices=[('person', 'personenbezogen'), ('familie', 'familienbezogen')], default='person', max_length=10)),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wirkungsdimension',
                'verbose_name_plural': 'Wirkungsdimensionen',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.AddField(
            model_name='historicalziel',
            name='erreicht_grad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Zielerreichung %'),
        ),
        migrations.AddField(
            model_name='ziel',
            name='erreicht_grad',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Zielerreichung %'),
        ),
        migrations.AlterField(
            model_name='historicalziel',
            name='art',
            field=models.CharField(choices=[('richtungsziel', 'Leitziel'), ('handlungsziel', 'Teilhabeziel (operational)')], default='handlungsziel', max_length=16),
        ),
        migrations.AlterField(
            model_name='ziel',
            name='art',
            field=models.CharField(choices=[('richtungsziel', 'Leitziel'), ('handlungsziel', 'Teilhabeziel (operational)')], default='handlungsziel', max_length=16),
        ),
        migrations.CreateModel(
            name='HistoricalWirkungseinschaetzung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('datum', models.DateField()),
                ('anlass', models.CharField(choices=[('beginn', 'Hilfebeginn (≤ 8 Wochen)'), ('fortschreibung', 'Fortschreibung / Hilfekonferenz'), ('ende', 'Beendigung der Hilfe')], default='fortschreibung', max_length=16)),
                ('perspektive', models.CharField(choices=[('fachkraft', 'Fachkraft Leistungserbringer'), ('klient', 'Klient*in / junger Mensch'), ('familie', 'Familie / Sorgeberechtigte'), ('kostentraeger', 'Fachkraft Jugendamt/THFD')], default='fachkraft', max_length=16)),
                ('ist', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Ist-Zustand (1–7)')),
                ('soll', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Soll bis zur nächsten Konferenz (1–7)')),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bericht', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.bericht')),
                ('erstellt_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
                ('dimension', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.wirkungsdimension')),
            ],
            options={
                'verbose_name': 'historical Wirkungseinschätzung',
                'verbose_name_plural': 'historical Wirkungseinschätzungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Wirkungseinschaetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('anlass', models.CharField(choices=[('beginn', 'Hilfebeginn (≤ 8 Wochen)'), ('fortschreibung', 'Fortschreibung / Hilfekonferenz'), ('ende', 'Beendigung der Hilfe')], default='fortschreibung', max_length=16)),
                ('perspektive', models.CharField(choices=[('fachkraft', 'Fachkraft Leistungserbringer'), ('klient', 'Klient*in / junger Mensch'), ('familie', 'Familie / Sorgeberechtigte'), ('kostentraeger', 'Fachkraft Jugendamt/THFD')], default='fachkraft', max_length=16)),
                ('ist', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Ist-Zustand (1–7)')),
                ('soll', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Soll bis zur nächsten Konferenz (1–7)')),
                ('kommentar', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('bericht', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wirkungseinschaetzungen', to='nachweis.bericht')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einschaetzungen', to='nachweis.wirkungsdimension')),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wirkungseinschaetzungen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Wirkungseinschätzung',
                'verbose_name_plural': 'Wirkungseinschätzungen',
                'ordering': ['-datum', 'dimension__reihenfolge'],
                'indexes': [models.Index(fields=['klient', 'dimension'], name='nachweis_wi_klient__c5bcd3_idx')],
            },
        ),
    ]
