# Generated by Django 5.2.15 on 2026-07-14 15:41

import django.db.models.deletion
import nachweis.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0040_wirkungsdimensionen_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('bescheid', 'Bewilligungsbescheid'), ('bericht', 'Bericht (unterschrieben)'), ('vertrag', 'Vertrag / WBVG'), ('schutz', 'Schutzkonzept / Vereinbarung'), ('sonstig', 'Sonstiges')], default='sonstig', max_length=12)),
                ('name', models.CharField(max_length=200, verbose_name='Anzeigename')),
                ('datei', models.FileField(max_length=255, upload_to=nachweis.models._dokument_pfad)),
                ('groesse', models.PositiveIntegerField(default=0, editable=False)),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('hochgeladen_am', models.DateTimeField(auto_now_add=True)),
                ('bewilligung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumente', to='nachweis.bewilligung', verbose_name='gehört zu Bewilligung')),
                ('hochgeladen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumente', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-hochgeladen_am'],
                'indexes': [models.Index(fields=['klient', 'kategorie'], name='nachweis_do_klient__dde11b_idx')],
            },
        ),
    ]
