# Generated by Django 5.2.15 on 2026-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0041_dokument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aufbewahrungsregel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('abrechnung', 'Abrechnung & Buchungsbelege'), ('leistungsnachweis', 'Leistungsnachweise'), ('kasse', 'Kassenbuch & Zählprotokolle'), ('fachdoku_egh', 'Fachakte Eingliederungshilfe (SGB IX)'), ('fachdoku_jug', 'Fachakte Jugendhilfe (SGB VIII)'), ('wtg', 'Dokumentation stationär (WTG Berlin)'), ('dokument', 'Abgelegte Dokumente'), ('personal', 'Arbeitszeit & Dienstplan')], max_length=20, unique=True)),
                ('bezeichnung', models.CharField(max_length=120)),
                ('jahre', models.PositiveSmallIntegerField(verbose_name='Aufbewahrung (Jahre)')),
                ('rechtsgrundlage', models.CharField(blank=True, max_length=160)),
                ('hinweis', models.CharField(blank=True, max_length=255)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Aufbewahrungsregel',
                'verbose_name_plural': 'Aufbewahrungsregeln (Löschkonzept)',
                'ordering': ['kategorie'],
            },
        ),
    ]
