# Generated by Django 5.2.15 on 2026-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0043_aufbewahrungsregeln_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbelegung',
            name='kommentar',
        ),
        migrations.RemoveField(
            model_name='historicalbewilligung',
            name='aktenzeichen',
        ),
        migrations.RemoveField(
            model_name='historicalbewilligung',
            name='kommentar',
        ),
        migrations.RemoveField(
            model_name='historicalziel',
            name='beschreibung',
        ),
        migrations.RemoveField(
            model_name='historicalziel',
            name='indikator',
        ),
        migrations.RemoveField(
            model_name='historicalziel',
            name='titel',
        ),
        migrations.AddField(
            model_name='klient',
            name='anonymisiert_am',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='anonymisiert am'),
        ),
    ]
