# Generated by Django 5.2.15 on 2026-07-14 18:25

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0044_remove_historicalbelegung_kommentar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSelbstzahlerRechnung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nummer', models.CharField(db_index=True, max_length=20, verbose_name='Rechnungsnummer')),
                ('empfaenger', models.CharField(max_length=140, verbose_name='Empfänger')),
                ('empfaenger_anschrift', models.TextField(blank=True, verbose_name='Anschrift')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('datum', models.DateField(verbose_name='Rechnungsdatum')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='fällig am')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gestellt', 'gestellt'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert')], default='gestellt', max_length=10)),
                ('bezahlt_am', models.DateField(blank=True, null=True, verbose_name='bezahlt am')),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('erstellt_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'historical Selbstzahler-Rechnung',
                'verbose_name_plural': 'historical Selbstzahler-Rechnungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWohnkostenvereinbarung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='gültig ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='gültig bis')),
                ('faelligkeit_tag', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='fällig am Tag des Monats')),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('angebot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.angebot', verbose_name='Wohnform')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'historical Wohnkostenvereinbarung',
                'verbose_name_plural': 'historical Wohnkostenvereinbarungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SelbstzahlerRechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20, unique=True, verbose_name='Rechnungsnummer')),
                ('empfaenger', models.CharField(max_length=140, verbose_name='Empfänger')),
                ('empfaenger_anschrift', models.TextField(blank=True, verbose_name='Anschrift')),
                ('jahr', models.PositiveIntegerField()),
                ('monat', models.PositiveSmallIntegerField()),
                ('datum', models.DateField(verbose_name='Rechnungsdatum')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='fällig am')),
                ('betrag', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gestellt', 'gestellt'), ('bezahlt', 'bezahlt'), ('storniert', 'storniert')], default='gestellt', max_length=10)),
                ('bezahlt_am', models.DateField(blank=True, null=True, verbose_name='bezahlt am')),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erstellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selbstzahler_rechnungen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Selbstzahler-Rechnung',
                'verbose_name_plural': 'Selbstzahler-Rechnungen',
                'ordering': ['-datum', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='SelbstzahlerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=140)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='nachweis.selbstzahlerrechnung')),
            ],
            options={
                'verbose_name': 'Selbstzahler-Position',
                'verbose_name_plural': 'Selbstzahler-Positionen',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wohnkostenvereinbarung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gueltig_von', models.DateField(blank=True, null=True, verbose_name='gültig ab')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='gültig bis')),
                ('faelligkeit_tag', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)], verbose_name='fällig am Tag des Monats')),
                ('aktiv', models.BooleanField(default=True)),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('angebot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wohnkosten', to='nachweis.angebot', verbose_name='Wohnform')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wohnkosten', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Wohnkostenvereinbarung',
                'verbose_name_plural': 'Wohnkostenvereinbarungen',
                'ordering': ['-gueltig_von', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Wohnkostenposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(choices=[('miete', 'Wohnraum / Grundmiete'), ('nebenkosten', 'Neben-/Betriebskosten'), ('verpflegung', 'Verpflegung'), ('investition', 'Investitionskosten'), ('barbetrag', 'Barbetrag / Weiteres'), ('sonstiges', 'Sonstiges')], default='miete', max_length=12)),
                ('bezeichnung', models.CharField(max_length=120)),
                ('monatsbetrag', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Betrag €/Monat')),
                ('vereinbarung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='nachweis.wohnkostenvereinbarung')),
            ],
            options={
                'verbose_name': 'Wohnkostenposition',
                'verbose_name_plural': 'Wohnkostenpositionen',
                'ordering': ['kategorie', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='selbstzahlerrechnung',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['entwurf', 'gestellt', 'bezahlt'])), fields=('klient', 'jahr', 'monat'), name='eine_selbstzahler_rechnung_je_klient_monat'),
        ),
    ]
