# Generated by Django 5.2.15 on 2026-07-14 19:45

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0045_historicalselbstzahlerrechnung_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TibLebensbereich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('icf_code', models.CharField(blank=True, max_length=6, verbose_name='ICF-Domäne')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0)),
                ('aktiv', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TIB-Lebensbereich',
                'verbose_name_plural': 'TIB-Lebensbereiche',
                'ordering': ['reihenfolge', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bedarfsermittlung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anlass', models.CharField(choices=[('erst', 'Erst-Bedarfsermittlung'), ('fortschreibung', 'Folge-Bedarfsermittlung (Fortschreibung)')], default='erst', max_length=16)),
                ('datum', models.DateField()),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erhoben_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedarfsermittlungen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Bedarfsermittlung (ICF/TIB)',
                'verbose_name_plural': 'Bedarfsermittlungen (ICF/TIB)',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBedarfsermittlung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('anlass', models.CharField(choices=[('erst', 'Erst-Bedarfsermittlung'), ('fortschreibung', 'Folge-Bedarfsermittlung (Fortschreibung)')], default='erst', max_length=16)),
                ('datum', models.DateField()),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('erhoben_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'historical Bedarfsermittlung (ICF/TIB)',
                'verbose_name_plural': 'historical Bedarfsermittlungen (ICF/TIB)',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBedarfsEinschaetzung',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('relevant', models.BooleanField(default=False, verbose_name='für diesen Fall relevant')),
                ('teilhabe_status', models.CharField(choices=[('offen', 'noch offen'), ('liegt_vor', 'Beeinträchtigung liegt vor'), ('droht', 'Beeinträchtigung droht'), ('keine', 'keine Beeinträchtigung')], default='offen', max_length=12)),
                ('unterstuetzung', models.CharField(blank=True, max_length=255, verbose_name='Unterstützungsbedarf (Art/Umfang, vorläufig)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bedarfsermittlung', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.bedarfsermittlung')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lebensbereich', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.tiblebensbereich')),
            ],
            options={
                'verbose_name': 'historical Bedarfs-Einschätzung',
                'verbose_name_plural': 'historical Bedarfs-Einschätzungen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BedarfsEinschaetzung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevant', models.BooleanField(default=False, verbose_name='für diesen Fall relevant')),
                ('gelingt', models.TextField(blank=True, verbose_name='Was gelingt / Ressourcen & Förderfaktoren')),
                ('barrieren', models.TextField(blank=True, verbose_name='Was nicht gelingt / Barrieren')),
                ('personfaktoren', models.TextField(blank=True, verbose_name='Personbezogene Faktoren / weiteres')),
                ('teilhabe_status', models.CharField(choices=[('offen', 'noch offen'), ('liegt_vor', 'Beeinträchtigung liegt vor'), ('droht', 'Beeinträchtigung droht'), ('keine', 'keine Beeinträchtigung')], default='offen', max_length=12)),
                ('unterstuetzung', models.CharField(blank=True, max_length=255, verbose_name='Unterstützungsbedarf (Art/Umfang, vorläufig)')),
                ('bedarfsermittlung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einschaetzungen', to='nachweis.bedarfsermittlung')),
                ('lebensbereich', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einschaetzungen', to='nachweis.tiblebensbereich')),
            ],
            options={
                'verbose_name': 'Bedarfs-Einschätzung',
                'verbose_name_plural': 'Bedarfs-Einschätzungen',
                'ordering': ['lebensbereich__reihenfolge'],
                'constraints': [models.UniqueConstraint(fields=('bedarfsermittlung', 'lebensbereich'), name='ein_lebensbereich_je_bedarfsermittlung')],
            },
        ),
    ]
