# Generated by Django 5.2.15 on 2026-07-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0047_tib_lebensbereiche_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='bewilligung',
            name='ptl',
            field=models.CharField(blank=True, choices=[('', 'keine'), ('A', 'PTL A (60 Min/Woche)'), ('B', 'PTL B (120 Min/Woche)')], default='', max_length=1, verbose_name='Psychotherapie (PTL)'),
        ),
        migrations.AddField(
            model_name='historicalbewilligung',
            name='ptl',
            field=models.CharField(blank=True, choices=[('', 'keine'), ('A', 'PTL A (60 Min/Woche)'), ('B', 'PTL B (120 Min/Woche)')], default='', max_length=1, verbose_name='Psychotherapie (PTL)'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='abrechenbare_fls',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='abrechenbare FLS (§ 18 Abs. 4)'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='ptl_betrag',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='PTL Betrag €'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='ptl_stunden',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=7, verbose_name='PTL Std/Monat'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='erbringungsfiktion',
            field=models.BooleanField(default=False, verbose_name='Erbringungsfiktion (§ 18 Abs. 4: Soll abrechnen)'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='ptl_preis',
            field=models.DecimalField(decimal_places=4, default=0, help_text='€ je Stunde für integrierte psychotherapeutische Leistung (PTL A/B). 0 = PTL nicht in der Abrechnung.', max_digits=8, verbose_name='PTL-Satz € (integrierte Psychotherapie)'),
        ),
    ]
