# Generated by Django 5.2.15 on 2026-07-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0048_bewilligung_ptl_historicalbewilligung_ptl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='abgerechnet_nach_soll',
            field=models.BooleanField(default=False, verbose_name='nach Soll abgerechnet (§ 18 Abs. 4)'),
        ),
    ]
