# Generated by Django 5.2.15 on 2026-07-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0049_monatsfreigabe_abgerechnet_nach_soll'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrechnung',
            name='gesendet_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='per E-Mail gesendet am'),
        ),
        migrations.AddField(
            model_name='historicalrechnung',
            name='gesendet_an',
            field=models.EmailField(blank=True, max_length=254, verbose_name='gesendet an'),
        ),
        migrations.AddField(
            model_name='historicalrechnung',
            name='gesendet_von',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter'),
        ),
        migrations.AddField(
            model_name='kostentraeger',
            name='email',
            field=models.EmailField(blank=True, help_text='Empfänger für den elektronischen Rechnungs-/Mahnungsversand', max_length=254, verbose_name='Rechnungs-E-Mail'),
        ),
        migrations.AddField(
            model_name='mahnung',
            name='gesendet_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='per E-Mail gesendet am'),
        ),
        migrations.AddField(
            model_name='mahnung',
            name='gesendet_an',
            field=models.EmailField(blank=True, max_length=254, verbose_name='gesendet an'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='gesendet_am',
            field=models.DateTimeField(blank=True, null=True, verbose_name='per E-Mail gesendet am'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='gesendet_an',
            field=models.EmailField(blank=True, max_length=254, verbose_name='gesendet an'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='gesendet_von',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter'),
        ),
    ]
