# Generated by Django 5.2.15 on 2026-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0050_historicalrechnung_gesendet_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='teiler_global',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Teiler Teamsitzung/Serien (global)'),
        ),
        migrations.AddField(
            model_name='monatsfreigabe',
            name='teiler_team',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Teiler team-bezogene Serien'),
        ),
    ]
