# Generated by Django 5.2.15 on 2026-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0051_monatsfreigabe_teiler_global_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monatsfreigabe',
            name='auto_zeilen',
            field=models.JSONField(blank=True, default=list, verbose_name='Auto-Nachweis-Zeilen (festgeschrieben)'),
        ),
    ]
