# Generated by Django 5.2.15 on 2026-07-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0052_monatsfreigabe_auto_zeilen'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='betreuung_bis',
            field=models.DateField(blank=True, null=True, verbose_name='Betreuung bestellt bis'),
        ),
        migrations.AddField(
            model_name='klient',
            name='betreuung_name',
            field=models.CharField(blank=True, max_length=140, verbose_name='gesetzliche Betreuung'),
        ),
        migrations.AddField(
            model_name='klient',
            name='betreuung_telefon',
            field=models.CharField(blank=True, max_length=80, verbose_name='Betreuung – Kontakt'),
        ),
        migrations.AddField(
            model_name='klient',
            name='betreuung_umfang',
            field=models.CharField(blank=True, max_length=200, verbose_name='Aufgabenkreise'),
        ),
        migrations.AddField(
            model_name='klient',
            name='ort',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='klient',
            name='plz',
            field=models.CharField(blank=True, max_length=10, verbose_name='PLZ'),
        ),
        migrations.AddField(
            model_name='klient',
            name='strasse',
            field=models.CharField(blank=True, max_length=160, verbose_name='Straße + Nr.'),
        ),
    ]
