# Generated by Django 5.2.15 on 2026-07-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0053_klient_betreuung_bis_klient_betreuung_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kontaktperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('angehoerige', 'Angehörige*r'), ('betreuung', 'gesetzliche Betreuung'), ('arzt', 'Arzt / Ärztin / Therapie'), ('notfall', 'Notfallkontakt'), ('behoerde', 'Behörde / Amt'), ('sonstig', 'Sonstige*r')], default='angehoerige', max_length=12)),
                ('name', models.CharField(max_length=140, verbose_name='Name')),
                ('funktion', models.CharField(blank=True, max_length=120, verbose_name='Funktion / Beziehung')),
                ('telefon', models.CharField(blank=True, max_length=60, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('adresse', models.CharField(blank=True, max_length=200, verbose_name='Anschrift')),
                ('notiz', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('notfall', models.BooleanField(default=False, verbose_name='Notfallkontakt')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kontakte', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Kontaktperson',
                'verbose_name_plural': 'Kontaktpersonen',
                'ordering': ['-notfall', 'rolle', 'name'],
                'indexes': [models.Index(fields=['klient', 'rolle'], name='nachweis_ko_klient__679663_idx')],
            },
        ),
    ]
