# Generated by Django 5.2.15 on 2026-07-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0054_kontaktperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitarbeiter',
            name='fachkraft',
            field=models.BooleanField(default=True, verbose_name='Fachkraft'),
        ),
        migrations.AddField(
            model_name='team',
            name='fachkraftquote',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Fachkraftquote (%)'),
        ),
    ]
