# Generated by Django 5.2.15 on 2026-07-15 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0055_mitarbeiter_fachkraft_team_fachkraftquote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualifikation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('quali', 'Berufsqualifikation / Abschluss'), ('fortbildung', 'Fortbildung'), ('zertifikat', 'Zertifikat / Nachweis'), ('pflicht', 'Pflichtunterweisung')], default='fortbildung', max_length=12)),
                ('bezeichnung', models.CharField(max_length=160, verbose_name='Bezeichnung')),
                ('erworben_am', models.DateField(blank=True, null=True, verbose_name='erworben am')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='gültig/Auffrischung bis')),
                ('pflicht', models.BooleanField(default=False, verbose_name='Pflichtfortbildung')),
                ('notiz', models.CharField(blank=True, max_length=200, verbose_name='Notiz')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('mitarbeiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifikationen', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Qualifikation',
                'verbose_name_plural': 'Qualifikationen',
                'ordering': ['gueltig_bis', 'bezeichnung'],
                'indexes': [models.Index(fields=['mitarbeiter', 'gueltig_bis'], name='nachweis_qu_mitarbe_7fc43a_idx')],
            },
        ),
    ]
