# Generated by Django 5.2.15 on 2026-07-15 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0056_qualifikation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belegung',
            name='platz',
            field=models.CharField(blank=True, max_length=40, verbose_name='Platz/Zimmer (Freitext)'),
        ),
        migrations.AlterField(
            model_name='historicalbelegung',
            name='platz',
            field=models.CharField(blank=True, max_length=40, verbose_name='Platz/Zimmer (Freitext)'),
        ),
        migrations.CreateModel(
            name='Zimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Zimmer-Nr / Name')),
                ('plaetze', models.PositiveSmallIntegerField(default=1, verbose_name='Plätze')),
                ('etage', models.CharField(blank=True, max_length=40, verbose_name='Etage / Bereich')),
                ('notiz', models.CharField(blank=True, max_length=120)),
                ('aktiv', models.BooleanField(default=True)),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zimmer', to='nachweis.angebot')),
            ],
            options={
                'verbose_name': 'Zimmer',
                'verbose_name_plural': 'Zimmer',
                'ordering': ['angebot', 'name'],
            },
        ),
        migrations.AddField(
            model_name='belegung',
            name='zimmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belegungen', to='nachweis.zimmer', verbose_name='Zimmer'),
        ),
        migrations.AddField(
            model_name='historicalbelegung',
            name='zimmer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.zimmer', verbose_name='Zimmer'),
        ),
        migrations.AddConstraint(
            model_name='zimmer',
            constraint=models.UniqueConstraint(fields=('angebot', 'name'), name='ein_zimmer_je_angebot_name'),
        ),
    ]
