# Generated by Django 5.2.15 on 2026-07-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0057_alter_belegung_platz_alter_historicalbelegung_platz_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klientenkonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('barbetrag', 'Barbetrag'), ('verwahrgeld', 'Verwahr-/Verfügungsgeld'), ('sonstig', 'Sonstiges Treuhandkonto')], default='barbetrag', max_length=12)),
                ('bezeichnung', models.CharField(blank=True, max_length=80, verbose_name='Bezeichnung')),
                ('aktiv', models.BooleanField(default=True)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konten', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Klientenkonto',
                'verbose_name_plural': 'Klientenkonten',
                'ordering': ['typ', 'bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Kontobuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Betrag € (+/−)')),
                ('zweck', models.CharField(max_length=160, verbose_name='Zweck / Verwendung')),
                ('beleg_nr', models.CharField(blank=True, max_length=40, verbose_name='Beleg-Nr')),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('konto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buchungen', to='nachweis.klientenkonto')),
            ],
            options={
                'verbose_name': 'Kontobuchung',
                'verbose_name_plural': 'Kontobuchungen',
                'ordering': ['-datum', '-id'],
            },
        ),
    ]
