# Generated by Django 5.2.15 on 2026-07-15 19:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0058_klientenkonto_kontobuchung'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFEM',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('art', models.CharField(choices=[('fixierung', 'Fixierung / Gurt'), ('bettgitter', 'Bettgitter'), ('medikamentoes', 'Medikamentös (sedierend)'), ('tuer', 'Verschlossene Tür / Ausgangssicherung'), ('sonstig', 'Sonstige')], default='fixierung', max_length=14)),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ende', models.DateTimeField(blank=True, help_text='leer = läuft noch', null=True, verbose_name='Ende')),
                ('angeordnet_von', models.CharField(blank=True, max_length=140, verbose_name='angeordnet von (Arzt/Betreuung)')),
                ('genehmigung_az', models.CharField(blank=True, max_length=80, verbose_name='richterliches Aktenzeichen (§ 1831 BGB)')),
                ('genehmigt_bis', models.DateField(blank=True, null=True, verbose_name='Genehmigung befristet bis')),
                ('einwilligung', models.BooleanField(default=False, verbose_name='Einwilligung der/des Betreuten/Betreuung')),
                ('gemeldet_am', models.DateField(blank=True, null=True, verbose_name='der Aufsicht (WTG) gemeldet am')),
                ('erstellt', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('erfasst_von', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.mitarbeiter')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'historical Freiheitsentziehende Maßnahme',
                'verbose_name_plural': 'historical Freiheitsentziehende Maßnahmen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FEM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('fixierung', 'Fixierung / Gurt'), ('bettgitter', 'Bettgitter'), ('medikamentoes', 'Medikamentös (sedierend)'), ('tuer', 'Verschlossene Tür / Ausgangssicherung'), ('sonstig', 'Sonstige')], default='fixierung', max_length=14)),
                ('beginn', models.DateTimeField(verbose_name='Beginn')),
                ('ende', models.DateTimeField(blank=True, help_text='leer = läuft noch', null=True, verbose_name='Ende')),
                ('grund', models.CharField(max_length=200, verbose_name='Grund / Gefährdung')),
                ('angeordnet_von', models.CharField(blank=True, max_length=140, verbose_name='angeordnet von (Arzt/Betreuung)')),
                ('genehmigung_az', models.CharField(blank=True, max_length=80, verbose_name='richterliches Aktenzeichen (§ 1831 BGB)')),
                ('genehmigt_bis', models.DateField(blank=True, null=True, verbose_name='Genehmigung befristet bis')),
                ('einwilligung', models.BooleanField(default=False, verbose_name='Einwilligung der/des Betreuten/Betreuung')),
                ('gemeldet_am', models.DateField(blank=True, null=True, verbose_name='der Aufsicht (WTG) gemeldet am')),
                ('notiz', models.CharField(blank=True, max_length=200)),
                ('erstellt', models.DateTimeField(auto_now_add=True)),
                ('erfasst_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fem_massnahmen', to='nachweis.klient')),
            ],
            options={
                'verbose_name': 'Freiheitsentziehende Maßnahme',
                'verbose_name_plural': 'Freiheitsentziehende Maßnahmen',
                'ordering': ['-beginn'],
                'indexes': [models.Index(fields=['klient', 'beginn'], name='nachweis_fe_klient__31b948_idx')],
            },
        ),
    ]
