# Generated by Django 5.2.15 on 2026-07-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0059_historicalfem_fem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zugriffslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bereich', models.CharField(choices=[('fallakte', 'Fallakte'), ('bericht', 'Bericht'), ('fem', 'FEM-Dokumentation'), ('bedarf', 'ICF-Bedarfsermittlung')], max_length=12)),
                ('zeit', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zugriffe', to='nachweis.klient')),
                ('mitarbeiter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nachweis.mitarbeiter')),
            ],
            options={
                'verbose_name': 'Zugriffsprotokoll-Eintrag',
                'verbose_name_plural': 'Zugriffsprotokoll (Lesezugriffe)',
                'ordering': ['-zeit'],
                'indexes': [models.Index(fields=['klient', '-zeit'], name='nachweis_zu_klient__932d78_idx'), models.Index(fields=['zeit'], name='nachweis_zu_zeit_8857d9_idx')],
            },
        ),
    ]
