# Generated by Django 5.2.15 on 2026-07-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nachweis', '0060_zugriffslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feiertagsanpassung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(unique=True, verbose_name='Datum')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Bezeichnung')),
                ('streichung', models.BooleanField(default=False, verbose_name='Streichung (Tag ist KEIN Feiertag)')),
            ],
            options={
                'verbose_name': 'Feiertags-Anpassung',
                'verbose_name_plural': 'Feiertags-Anpassungen',
                'ordering': ['datum'],
            },
        ),
    ]
