"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import mimetypes
import os
from pathlib import Path

# PWA-Manifest mit korrektem Content-Type ausliefern
mimetypes.add_type("application/manifest+json", ".webmanifest", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Konfiguration über Umgebungsvariablen (Prod), mit Entwicklungs-Defaults.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-2wy*qhe^xuv77nl%1*ep#9xxekbamj7ib#ki#e=)d27l^ye9q_")

DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

# Fail-closed: Sobald Produktions-Indikatoren gesetzt sind (echte DB oder ALLOWED_HOSTS),
# läuft die Instanz NIE im Debug-Modus – auch wenn DJANGO_DEBUG versehentlich fehlt/vertippt
# ist. So kann ein Deploy-Konfigfehler keine offene Debug-Instanz mit Dev-Key erzeugen.
if DEBUG and (os.environ.get("DATABASE_URL") or os.environ.get("DJANGO_ALLOWED_HOSTS")):
    DEBUG = False

# In Produktion NIEMALS mit dem unsicheren Dev-Key laufen (fail-closed).
if not DEBUG and not os.environ.get("DJANGO_SECRET_KEY"):
    from django.core.exceptions import ImproperlyConfigured
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY muss in Produktion (DEBUG=0) gesetzt sein.")

ALLOWED_HOSTS = [h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h] \
    or (["*"] if DEBUG else [])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',
    'axes',            # Brute-Force-Schutz (Login-Lockout)
    'auditlog',        # Revisionssichere Änderungsprotokollierung
    'nachweis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'nachweis.middleware.CSPMiddleware',               # Content-Security-Policy (Report-Only default)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',            # NACH AuthenticationMiddleware
    'nachweis.middleware.InaktivitaetsAbmeldung',     # Auto-Logout bei Inaktivität
    'nachweis.middleware.OTPErzwingenMiddleware',     # NACH OTPMiddleware
    'auditlog.middleware.AuditlogMiddleware',         # Actor (request.user) für das Audit-Log
    'nachweis.middleware.RLSKontext',                 # PostgreSQL Row-Level-Security-Kontext (opt-in)
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',                 # MUSS als letzte Middleware laufen
]

# django-axes braucht seinen Auth-Backend VOR dem Standard-Backend
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Projekt-Templates zuerst durchsuchen -> Override von admin/base_site.html greift
        'DIRS': [BASE_DIR / 'nachweis' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'nachweis.context.globale',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Login
LOGIN_URL = 'nachweis:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'nachweis:login'

# Aktivierungs-/Passwort-Reset-Links: 7 Tage gültig (einmalig durch Token-Mechanik)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 7

# Automatische Abmeldung nach Inaktivität (Sekunden). Bei besonders sensiblen Daten
# üblich 10–15 Min. Serverseitig erzwungen (Middleware) + clientseitiger Timer.
SESSION_IDLE_TIMEOUT = int(os.environ.get("DJANGO_IDLE_TIMEOUT_MIN", "15")) * 60

# E-Mail (für optionalen Versand der Aktivierungslinks).
# Dev: Konsole (Link landet im Terminal). Prod: SMTP via Env-Variablen.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("DJANGO_EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("DJANGO_EMAIL_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("DJANGO_EMAIL_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("DJANGO_EMAIL_TLS", "1") == "1"
DEFAULT_FROM_EMAIL = os.environ.get("DJANGO_FROM_EMAIL", "FEGH-Leistungsnachweis <noreply@localhost>")
# E-Mail-Versand nur, wenn konfiguriert (Konsole zählt als "verfügbar" für Dev-Test)
EMAIL_AKTIV = bool(EMAIL_HOST) or EMAIL_BACKEND.endswith("console.EmailBackend")

# Externes Wiki (Material for MkDocs, GitHub Pages) – Link in der Sidebar
WIKI_URL = os.environ.get("WIKI_URL", "https://miri2577.github.io/FEGH-Leistungsnachweis/")

# Absender (Trägeranschrift) auf Rechnungen – mehrzeilig via Env (\n). Leer = Platzhalter.
RECHNUNG_ABSENDER = os.environ.get("RECHNUNG_ABSENDER", "").replace("\\n", "\n")

# Content-Security-Policy: Standard Report-Only (bricht nichts, meldet nur Verstöße).
# Erst eine Weile beobachten, dann DJANGO_CSP_ENFORCE=1 zum scharf schalten.
CSP_ENFORCE = os.environ.get("DJANGO_CSP_ENFORCE", "0") == "1"
CSP_REPORT_URI = os.environ.get("DJANGO_CSP_REPORT_URI", "")

# Zwei-Faktor (django-otp / TOTP)
OTP_TOTP_ISSUER = "FEGH-Leistungsnachweis"     # Anzeigename in der Authenticator-App
# Prototyp: 0 = optional (Opt-in, wer ein Gerät einrichtet wird gefragt).
# Prod: DJANGO_OTP_REQUIRED=1 -> Pflicht für ALLE (außer Break-Glass-Superuser).
OTP_REQUIRED = os.environ.get("DJANGO_OTP_REQUIRED", "0") == "1"

# --- Brute-Force-Schutz (django-axes) ---
AXES_FAILURE_LIMIT = int(os.environ.get("DJANGO_AXES_FAILURE_LIMIT", "5"))
AXES_COOLOFF_TIME = int(os.environ.get("DJANGO_AXES_COOLOFF_HOURS", "1"))  # Stunden bis Auto-Entsperrung
AXES_RESET_ON_SUCCESS = True                    # erfolgreicher Login setzt den Zähler zurück
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # sperrt die Kombination, nicht ganze NATs
AXES_ENABLE_ADMIN = True
AXES_VERBOSE = True

# --- Änderungs-/Zugriffsprotokoll (django-auditlog) ---
# Wer wann welche besonders sensiblen Datensätze angelegt/geändert/gelöscht hat.
AUDITLOG_INCLUDE_TRACKING_MODELS = (
    "nachweis.Klient",
    "nachweis.Leistung",
    "nachweis.Gruppe",
    "nachweis.Arbeitszeit",
    "nachweis.Abwesenheit",
    "nachweis.Kassenbuchung",
    "nachweis.Zaehlprotokoll",
    "nachweis.Mitarbeiter",
    "nachweis.Termin",
)

# =====================================================================
#  PRODUKTION (greift nur bei DEBUG=False; lokal bleibt alles unverändert)
# =====================================================================
# CSRF muss die HTTPS-Origin kennen (Django 4+)
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# PostgreSQL aus Umgebungsvariable (nur wenn gesetzt -> lokal weiter SQLite)
if os.environ.get("DATABASE_URL"):
    import dj_database_url
    DATABASES["default"] = dj_database_url.parse(
        os.environ["DATABASE_URL"], conn_max_age=600, ssl_require=False)

# Argon2 als bevorzugter Passwort-Hash (argon2-cffi)
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

if not DEBUG:
    # Statische Dateien über WhiteNoise (direkt nach der SecurityMiddleware)
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }
    # Caddy terminiert TLS und setzt X-Forwarded-Proto
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # Hinter Caddy (genau EIN Proxy) die ECHTE Client-IP ermitteln. Ohne das sähe axes
    # nur die interne Caddy-Container-IP -> Lockout degeneriert zu Username-only
    # (gezielter Login-DoS aufs Team) und die Angreifer-IP fehlt in jedem Log.
    AXES_IPWARE_PROXY_COUNT = 1
    AXES_IPWARE_META_PRECEDENCE_ORDER = ["HTTP_X_FORWARDED_FOR", "REMOTE_ADDR"]
    # HSTS – auf dem Server zunächst kurz (300) testen, dann 1 Jahr:
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    # Cookies nur über HTTPS, nicht per JS lesbar
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    # Sensible Daten: Session an den Arbeitstag koppeln
    SESSION_COOKIE_AGE = 60 * 60 * 8
    SESSION_EXPIRE_AT_BROWSER_CLOSE = True

    _log_file = os.environ.get("DJANGO_LOG_FILE", str(BASE_DIR / "logs" / "django.log"))
    os.makedirs(os.path.dirname(_log_file), exist_ok=True)
    LOGGING = {
        "version": 1, "disable_existing_loggers": False,
        "handlers": {"file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": _log_file,
            "maxBytes": 5_000_000, "backupCount": 10,
        }},
        "loggers": {
            "django.security": {"handlers": ["file"], "level": "INFO"},
            "django.request": {"handlers": ["file"], "level": "WARNING"},
        },
    }
